/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerFrame.java
 *
 * Created on Oct 6, 2010, 10:46:46 PM
 */

package server.gui;

import server.game.GameController;
import server.game.PlayerHandler;

import java.net.ServerSocket;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Minjie
 */
public class ServerFrame extends javax.swing.JFrame {

	/** Creates new form ServerFrame */
	public ServerFrame() {
		try{
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		setLocation(200, 50);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		start = new javax.swing.JButton();
		stop = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Stratego Server");

		start.setText("Start Server");
		start.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				startActionPerformed(evt);
			}
		});

		stop.setText("Stop Server");
		stop.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				stopActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGap(27, 27, 27)
						.addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
						.addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(31, 31, 31))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(55, 55, 55)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(stop, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
								.addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(41, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void startActionPerformed(java.awt.event.ActionEvent evt) {
		new Thread(){
			public void run(){
				try{
					start.setEnabled(false);
					int games=0;
					ServerSocket s = new ServerSocket(port);
					agc.add(new GameController());
					agc.get(games).start();
					agc.get(games).message("Server started at port " + port);
					while (true){
						PlayerHandler p = new PlayerHandler (s.accept(), agc.get(games), seq, "Player " + (seq++));
						if(seq%2==0)
						{
							agc.add(new GameController());
							games++;
							seq = (byte) (seq%2);
							agc.get(games).start();
							agc.get(games).message("Server started at port " + port);
						}
						p.start();
					}
				}catch(Exception e){JOptionPane.showMessageDialog(null,e);}
			}}.start();
	}

	private void stopActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ServerFrame().setVisible(true);
			}
		});
	}

	private static int port = 30568;
	private static byte seq = 0;
	private GameController game;
	private static ArrayList<GameController> agc = new ArrayList<GameController>();

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton start;
	private javax.swing.JButton stop;
	// End of variables declaration//GEN-END:variables

}
