/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimeCapsule.java
 *
 * Created on Apr 27, 2010, 3:38:18 PM
 */

package client.gui;

import client.protocol.C6Forfeit;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author mz1
 */
public class TimeCapsule extends javax.swing.JFrame {

	private Timer t;
	private int sec = 45;
	private MainFrame mf;


	/** Creates new form TimeCapsule */
	public TimeCapsule(MainFrame m) {
		try{
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		}
		catch(Exception e)
		{
		}
		mf=m;
		initComponents();
		t = new Timer(1000, new ActionListener(){
			public void actionPerformed(ActionEvent e)
			{
				if(sec>0)
				{
					sec--;
					updateTimer();
					if(sec==0)
						mf.getClientConnect().getOutput().send(new C6Forfeit(new byte[]{1}));
				}
			}
		});
	}

	public void startTimer()
	{
		t.start();
	}

	public void stopTimer()
	{
		t.stop();
	}
	
	public void resetTimer()
	{
		sec = 45;
	}

	private void updateTimer()
	{
		time.setText(sec / 60 + ":" + ((sec % 60 + 100) + "").substring(1));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		time = new javax.swing.JLabel();
		moreTimebutton = new javax.swing.JButton();
		requestLabel = new javax.swing.JLabel();
		timenum = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("Time Capsule");
		setResizable(false);

		time.setFont(new java.awt.Font("Segoe UI", 1, 36));
		time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		time.setText("0:45");
		time.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));

		moreTimebutton.setText("I fail so i need more time!");
		moreTimebutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				moreTimebuttonActionPerformed(evt);
			}
		});

		requestLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		requestLabel.setText("Time Request Left:");

		timenum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		timenum.setText("5");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGap(62, 62, 62)
										.addComponent(moreTimebutton))
										.addGroup(layout.createSequentialGroup()
												.addGap(40, 40, 40)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGap(38, 38, 38)
																.addComponent(requestLabel)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(timenum))
																.addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
																.addContainerGap(49, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(57, 57, 57)
						.addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(timenum)
								.addComponent(requestLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(moreTimebutton)
								.addGap(26, 26, 26))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void moreTimebuttonActionPerformed(java.awt.event.ActionEvent evt) {
		int value = Integer.parseInt(timenum.getText());
		if(value>0){
			timenum.setText(Integer.toString(--value));
			sec+=15;
			updateTimer();
		}
	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton moreTimebutton;
	private javax.swing.JLabel requestLabel;
	private javax.swing.JLabel time;
	private javax.swing.JLabel timenum;
	// End of variables declaration//GEN-END:variables

}
